steps:
  # 1️⃣ Build Docker image con tag dinámico
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        IMAGE_TAG=$(date +%s)
        echo "Usando IMAGE_TAG=$$IMAGE_TAG"
        docker build -f slim.dockerfile -t us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:$$IMAGE_TAG .
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:$$IMAGE_TAG
        docker tag us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:$$IMAGE_TAG us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:latest

        echo $$IMAGE_TAG > /workspace/image_tag.txt

  # 2️⃣ Terraform Init
  - name: "hashicorp/terraform:1.13.4"
    id: "terraform init"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace/IaC-Quality/
        terraform init -backend-config="bucket=$_TF_STATE_BUCKET"

  # 3️⃣ Terraform Validate
  - name: "hashicorp/terraform:1.13.4"
    id: "terraform validate"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace/IaC-Quality/
        terraform validate


  # 4️⃣ Terraform Plan
  - name: "hashicorp/terraform:1.13.4"
    id: "terraform plan"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace/IaC-Quality/
        IMAGE_TAG=$(cat /workspace/image_tag.txt)
        terraform plan -out=tfplan -var "image_tag=$$IMAGE_TAG"

  - name: "hashicorp/terraform:1.13.4"
    id: "terraform destroy"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace/IaC-Quality/
        terraform destroy -auto-approve tfplan

  # 5️⃣ Terraform Apply
  - name: "hashicorp/terraform:1.13.4"
    id: "terraform apply"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd /workspace/IaC-Quality/
        IMAGE_TAG=$(cat /workspace/image_tag.txt)
        terraform apply -auto-approve tfplan

# Imagen final para Cloud Build
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/quality-rules-load/quality-rules-load:latest"

# Opciones de logging
options:
  logging: CLOUD_LOGGING_ONLY

# Service account que ejecuta el build
serviceAccount: "cloudbuild-terraform@$PROJECT_ID.iam.gserviceaccount.com"

substitutions:
  _TF_STATE_BUCKET: "quality-rules-terraform-state"